name: fruit_store_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Network & API
  http: ^1.1.0
  signalr_netcore: ^1.3.5
  
  # Storage & State Management
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  
  # Utilities
  diacritic: ^0.1.3
  intl: ^0.20.2
  logging: ^1.2.0
  
  # UI
  iconsax: 0.0.8
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  fl_chart: ^0.70.0
  
  # Image & Media
  image_picker: ^1.0.4
  
  # Payment
  flutter_stripe: ^11.1.0
  flutter_markdown: ^0.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/lg3.png"
  adaptive_icon_background: "#1A5F3A"
  adaptive_icon_foreground: "lib/assets/img/lg3.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/img/bn1.png
    - lib/assets/img/bn2.png
    - lib/assets/img/bn3.png
    - lib/assets/img/logo1.png
    - lib/assets/img/logo.png
    - lib/assets/icon/google.png
    - lib/assets/img/giaychungnhan.png